### ISSUE TITLE
Phase 1 configuration invariant and minimal config

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#1974]
I just found that some BLS-enabled tests are broken. (The CI is running with `--disable-bls` flag) Some Issue 1 showed up after I enabled BLS. And then Issue 1 revealed Issue 2 and Issue 3.

### [FIXED] Issue 1. Suggestion: `EPOCHS_PER_CUSTODY_PERIOD` should be smaller than `EPOCHS_PER_HISTORICAL_VECTOR`. -> fixed in #1990

From the test cases, my understanding is that the period of valid `custody_slashing: SignedCustodySlashing` is that `compute_epoch_at_slot(custody_slashing.attestation.data.slot) + EPOCHS_PER_CUSTODY_PERIOD < get_current_epoch(state)`, where the `state` is the beacon state processing `SignedCustodySlashing`.
In [process_custody_slashing](https://github.com/ethereum/eth2.0-specs/blob/3e9556202a5535be87e2189c90330f75c5e3c014/specs/phase1/custody-game.md#custody-slashings), it needs to use `state.randao_mixes` to get the seed to verify the `custody_slashing.attestation`. Due to `MIN_SEED_LOOKAHEAD`, the acceptable `SignedCustodySlashing`  has to satisfy `compute_epoch_at_slot(custody_slashing.attestation.data.slot) + EPOCHS_PER_CUSTODY_PERIOD - MIN_SEED_LOOKAHEAD < get_current_epoch(state)`.

#### Proposal

To fix it easily, we can increase `EPOCHS_PER_HISTORICAL_VECTOR` to `128` or decrease `EPOCHS_PER_CUSTODY_PERIOD` to `32`. However, when I set `EPOCHS_PER_CUSTODY_PERIOD` to `32`, some other tests broke. That's another different issue. (see Issue 3 below)

---

### [FIXED] Issue 2. Suggestion: set minimal config numbers in a similar ratio of the mainnet config. -> fixed in #1990

For example:
- In minimal config, `EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS = MAX_CHUNK_CHALLENGE_DELAY = 128 > EPOCHS_PER_HISTORICAL_VECTOR = 64`
- In mainnet config, `EPOCHS_PER_HISTORICAL_VECTOR = 65536 > EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS = MAX_CHUNK_CHALLENGE_DELAY > EPOCHS_PER_HISTORICAL_VECTOR = 32768`.

It would be better to keep the same ratio or the same order when we scale down the numbers.

#### Proposal

Adjust the numbers carefully. This branch is my current trial: https://github.com/ethereum/eth2.0-specs/compare/6a7a47dd5f6ce39cb8fcdbf787325886140191c3...hwwhww/fix-body-root

---

### Issue 3. Some block processing custody test cases trigger reveal-deadlines-slashing

It's not mainly due to the config numbers failure, but changing config numbers would reveal this issue in some test cases.

For example, [`test_process_custody_slashing.py::test_many_epochs_custody`](https://github.com/ethereum/eth2.0-specs/blob/8a2132e65df19643e7c10be93be5451e4eb501aa/tests/core/pyspec/eth2spec/test/phase1/block_processing/test_process_custody_slashing.py#L126) calls [transition_to(spec, state, state.slot + spec.SLOTS_PER_EPOCH * (spec.EPOCHS_PER_CUSTODY_PERIOD - 1))
](https://github.com/ethereum/eth2.0-specs/blob/8a2132e65df19643e7c10be93be5451e4eb501aa/tests/core/pyspec/eth2spec/test/phase1/block_processing/test_process_custody_slashing.py#L95), which would trigger **the epoch processing**. Some validators may get slashed in `process_reveal_deadlines`.

And when we run `process_custody_slashing`, it checks `assert is_slashable_validator(whistleblower, get_current_epoch(state))` and `assert is_slashable_validator(malefactor, get_current_epoch(state))`. The whistleblower and malefactor may have been slashed by `process_reveal_deadlines`, which is not this test case aim to do.

---

### Reference

The current mainnet config:
```yaml
# Phase 0
# 2**16 (= 65,536) epochs ~0.8 years
EPOCHS_PER_HISTORICAL_VECTOR: 65536
# 2**13 (= 8,192) epochs ~36 days
EPOCHS_PER_SLASHINGS_VECTOR: 8192

# Phase 1
# Time parameters
# 2**1 (= 2) epochs, 12.8 minutes
RANDAO_PENALTY_EPOCHS: 2
# 2**15 (= 32,768) epochs, ~146 days
EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS: 32768
# 2**14 (= 16,384) epochs ~73 days
EPOCHS_PER_CUSTODY_PERIOD: 16384
# 2**11 (= 2,048) epochs, ~9 days
CUSTODY_PERIOD_TO_RANDAO_PADDING: 2048
# 2**15 (= 32,768) epochs, ~146 days
MAX_CHUNK_CHALLENGE_DELAY: 32768
```

The current minimal config:
```yaml
# Phase 0
# [customized] smaller state
EPOCHS_PER_HISTORICAL_VECTOR: 64
# [customized] smaller state
EPOCHS_PER_SLASHINGS_VECTOR: 64

# Phase 1
# Time parameters
# 2**1 (= 2) epochs
RANDAO_PENALTY_EPOCHS: 2
# [customized] quicker for testing
EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS: 128
# [customized] quicker for testing
EPOCHS_PER_CUSTODY_PERIOD: 64
# [customized] quicker for testing
CUSTODY_PERIOD_TO_RANDAO_PADDING: 8
# [customize for faster testing]
MAX_CHUNK_CHALLENGE_DELAY: 128
```

---

p.s. I haven't completed running custody tests with mainnet config; my laptop is screaming. I'll try to see what I can do with it next week.
