### ISSUE TITLE
Lightweight state-machine testing

### ISSUE THREAD

**Issue by moodmosaic** [ethereum/consensus-specs#4228]
Has there been consideration for adding state-machine testing to (dynamically) test consensus logic (validators, epochs, state transitions, rewards/penalties, etc.)?

For example, a small YAML scenario might look like:

```yaml
scenario:
  initial_state:
    validators:
      - {id: 1, balance: 32, active: true}
      - {id: 2, balance: 32, active: true}
  actions:
    - action: propose_block
      params: { proposer: "random" }
    - action: slash_validator
      params: { validator: "random" }
  invariants:
    - no_negative_balance
    - total_balance_properly_accounted
```

This could even use facilities from property-based testing tools (like Hypothesis) to:

1. Help generate diverse sequences of state transitions
2. Verify state invariants across all transitions
3. Replay any found edge cases

The real value here is finding minimal sequences that trigger consensus failures between the spec and implementations.

---

When client behavior diverges from the specification, state-machine testing could even (try to) *reduce* complex failure cases to the smallest possible reproducing example.

I think, in any case, this approach can help generate test vectors that are compatible with existing client test runners, maintaining the current workflow while expanding test coverage.

Open to feedback, I might have I've missed context or existing efforts.
